dev/askcompany/askcompany/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
# from django.conf.urls import url
from django.conf.urls.static import static
from django.views.generic import TemplateView,RedirectView

class RootView(TemplateView):
    template_name = 'root.html'
urlpatterns = [
    path('',RedirectView.as_view(
        # url="/instagram/",\
        # pattern 시스템으로 하는것을 선호한다.
        pattern_name="instagram:post_list"),name='root'),
    path('admin/', admin.site.urls), #URL_Reverse
    path('accounts/',include('accounts.urls')),
    path('blog1/',include('blog1.urls')),
    path('instagram/',include('instagram.urls')),
]


# settings.MEDIA_URL
# settings.MEDIA_URL

if settings.DEBUG :
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

dev/askcompany/blog1/urls.py
from . import views
from django.urls import path

app_name = "blog1"
urlpatterns = [
    path("", views.post_list, name="post_list"),
]

dev/askcompany/instagram/urls.py
from django.urls import path, re_path, register_converter

from . import views
from .converters import YearConverter,MonthConverter,DayConverter



register_converter(YearConverter, "year")
register_converter(MonthConverter, "month")
register_converter(DayConverter, "day")

app_name = "instagram"  # URL Reverse에서namespace역할을 한다.
urlpatterns = [
    path('new/',views.post_new,name='post_new'),
    path("", views.post_list,name="post_list"),
    path("<int:pk>/edit/", views.post_edit,name="post_edit"),  # int로 넘어감
    path("<int:pk>/delete/", views.post_delete,name="post_delete"),  # int로 넘어감
    path("<int:pk>/", views.post_detail,name="post_detail"),  # int로 넘어감
    # re_path(r'(?P<pk>\d+)/$',views.post_detail),  #str로 넘어감
    # path("archives/<int:year>/", views.archives_year),
    # re_path(r"archives/(?P<year>20\d{2})/", views.archives_year),
    # r 을쓰면 \ 를 자동 이스케이프 해준다.
    # path("archives/<year:year>/", views.archives_year),
    path ('archive/',views.post_archive, name='post_archive'),
    path('archive/<year:year>/',views.post_archive_year,name='post_archive_year'),
    # path('archive/<year:year>/<month:month>/',views.post_archive_month,name='post_archive_month'),
    # path('archive/<year:year>/<month:month>/<day:day>/',views.post_archive_day,name='post_archive_day'),
    
]

dev/askcompany/instagram/models.py
from django.db import models
import os
from django.core.validators import MinLengthValidator
from django.conf import settings
from django.urls import reverse

# min_length_validator = MinLengthValidator(3)  # 3글자 이하로 받으면 에러를 표현한다. 
# from uuid import uuid4
# from django.utils import timezone
# Create your models here.

class Post(models.Model) :
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    message = models.TextField(
        validators=[MinLengthValidator(10)]
    )
    photo = models.ImageField(blank=True,upload_to='instagram/post/%Y/%m/%d')
    tag_set = models.ManyToManyField('Tag',blank=True) 
    # blank 를 참으로 하는 이유는 태그는 없는 상황이 있을수도 있기 떄문에 
    # balnk=True 를 넣는다.                                                 
    is_public = models.BooleanField(default=False,verbose_name='공개 여부')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # JAVA의 toString
    def __str__(self):
        # return f"Custom Post object({self.id})"
        return self.message
    
    def get_absolute_url(self):
        return reverse("instagram:post_detail", args=[ self.pk])
    
    class Meta :
        ordering = ['-id']
    # def message_length(self):
    #     return len(self.message)
    # message_length.short_description = "메세지 글자수"
    # def uuid_name_upload_to(instance, filename):
    #     app_label = instance.__class__._meta.app_label # 앱 별로
    #     cls_name = instance.__class__.__name__.lower() # 모델 별로
    #     ymd_path = timezone.now().strftime('%Y/%m/%d') # 업로드하는 년/월/일 별로
    #     uuid_name = uuid4().hex
    #     extension = os.path.splitext(filename)[-1].lower() # 확장자 추출하고, 소문자로 변환
    #     return '/'.join([
    #     app_label,
    #     cls_name,
    #     ymd_path,
    #     uuid_name[:2],
    #     uuid_name + extension,
    #     ])

class Comment(models.Model) :
    # 다른앱의 모델을 지정하려면 instagram.Post 하듯이 하면 된다.
    post = models.ForeignKey('instagram.Post', on_delete=models.CASCADE,
    limit_choices_to={'is_public': True}) # 외래키 만들기 post_id
    
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    pass
class Tag(models.Model) :
    name = models.CharField(max_length=50,unique=True)
    # post_set = models.ManyToManyField(Post)
    def __str__(self):
        return self.name

dev/askcompany/instagram/forms.py
from django import forms
from .models import Post 
import re


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields= [
            
            'message',
            'photo',
            'tag_set',
        'is_public',
        ]
        #exclude = [] 배제한다.
    def clean_message(self):
        message = self.cleaned_data.get('message')
        if message :
            message =re.sub(r'[a-zA-Z]+','',message)
            len(message) > 20
        return message 

dev/askcompany/instagram/views.py
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView,DetailView,ArchiveIndexView,YearArchiveView,CreateView,UpdateView,DeleteView
from django.shortcuts import render , get_object_or_404,redirect
from .models import Post
from django.http import HttpResponse, HttpRequest,Http404
from django.utils.decorators import method_decorator
from .forms import PostForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.urls import reverse,reverse_lazy
# Create your views here.

# @login_required
# def post_new(request):
#     if request.method =='POST' :
#         form = PostForm(request.POST,request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user # 현재 로그인 User Instance
#             post.save()
#             messages.success(request,'포스팅을 저장했습니다.')
#             return redirect(post)
#     else :
#         form = PostForm()
   
#     return render(request,'instagram/post_form.html',{
#         'form':form,
#         'post':None,
#     })

class PostCreateView(LoginRequiredMixin,CreateView):
    model =Post
    form_class= PostForm
    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        messages.success(self.request,'포스팅을 저장했습니다.')
        return super().form_valid(form)
    
post_new = PostCreateView.as_view()
    
# post_list = ListView.as_view(model = Post)  # 클래스형

# @login_required
# def post_edit(request,pk):
#     post = get_object_or_404(Post,pk=pk)
    
#     # 작성자 Check Tip

#     if post.author != request.user :
#         messages.error(request,'작성자만 수정할 수 있습니다.')
#         return redirect(post)
#     if request.method =='POST' :
#         form = PostForm(request.POST,request.FILES, instance=post)
#         if form.is_valid():
#             post = form.save()
#             messages.success(request,'포스팅을 수정했습니다.')
#             return redirect(post)
#     else :
#         form = PostForm(instance=post)
   
#     return render(request,'instagram/post_form.html',{
#         'form':form,
#         'post':None,
#     })
########################################3
class PostUpdateView(LoginRequiredMixin,UpdateView):
    model =Post
    form_class= PostForm
    def form_valid(self,form):
        messages.success(self.request,'포스팅을 수정했습니다.')
        return super().form_valid(form)
        
        
    
post_edit = PostUpdateView.as_view()

#####################################3
# def post_delete(request,pk):
#     post = get_object_or_404(Post,pk=pk)
#     if request.method == 'POST' :
#         post.delete()
#         messages.success(request,"포스팅을 삭제했습니다.")
#         return redirect('instagram:post_list')
        
#     return render(request,'instagram/post_confirm_delete.html', {
#         'post':post,
#     })
####################################3
class PostDeleteView(LoginRequiredMixin,DeleteView) :
    model =Post
    # success_url  = reverse('instagram:post_list') # 동작하지 않는다
    success_url  = reverse_lazy('instagram:post_list') # 동작하지 않는다
    # def get_success_url(self):
    #     return reverse('instagram:post_list')

post_delete = PostDeleteView.as_view()
    # TODO


# class ItemListView(ListView):
#     model = Post
#     paginate_by=10


# post_list = ItemListView.as_view()
# post_list = login_required(post_list)
########################################
# @method_decorator(login_required,name = 'dispatch')
# class PostListView(ListView):
#     model = Post
#     paginate_by =10
# post_list=  PostListView.as_view()
########################################
@login_required
def post_list(request) :   # 함수형
    qs = Post.objects.all()
    q = request.GET.get('q','')
    if q :
        qs = qs.filter(message__icontains =q)

    

    # instagram/templates/instagram/post_list.html
    return render(request , 'instagram/post_list.html',{
        'post_list': qs,
        'q':q,
    })


# def post_detail(request: HttpResponse, pk: int) -> HttpResponse:
#     # try :
#     #     post = Post.objects.get(pk=pk) # DoesNotExist 예외
#     # except Post.DoesNotExist :
#     #     raise Http404
#     post = get_object_or_404(Post,pk=pk)
#     return render(request, "instagram/post_detail.html", {"post": post,})


# post_detail = DetailView.as_view(
    
#     model=Post,
#     queryset=Post.objects.filter(is_public=True))
class PostDetailView(DetailView):
    model =Post
    # queryset = Post.objects.filter(is_public=True)
    def  get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_authenticated :
            qs = qs.filter(is_public=True)
        
            
        return qs
post_detail =  PostDetailView.as_view()    
# def archives_year(request, year):
#     return HttpResponse(f"{year}년 archives")


post_archive = ArchiveIndexView.as_view(model=Post , date_field ='created_at',paginate_by =10)

post_archive_year =YearArchiveView.as_view(model=Post,date_field='created_at',make_object_list=True)

dev/askcompany/instagram/templates/instagram/layout.html
{% load bootstrap4 static %}
<!doctype html>
<html lang='ko'>
    <head>
        <meta charset="utf-8"/>
        <meta
            name="viewport"
            content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
        <title>
            {% block title %}{% endblock title %}
        </title>
        <link
            rel="stylesheet"
            href="{% static 'bootstrap-4.5.3-dist/css/bootstrap.css' %}"/>
        <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
        <script>
            src = "{% static 'jquery.csrf.js' %} "
        </script>
        <script src="{% static 'bootstrap-4.5.3-dist/js/bootstrap.js'%}"></script>
        <style>
            body {
                padding-top: 5rem;
                padding-bottom: 2rem;
            }
        </style>
    </head>
    <body>

        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="#">Fixed navbar</a>
            <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarCollapse"
                aria-controls="navbarCollapse"
                aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home
                            <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input
                        class="form-control mr-sm-2"
                        type="text"
                        placeholder="Search"
                        aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>

        <div class="container">
            <div class="row">
                <div class="col-sm-12">

                    {% comment %} {% if messages %}
                        <div class="messages">
                            {% for message in messages %}
                                <div class='alert alert-{{message.tags}}'>
                                    {{message.message}}

                                </div>
                            {% endfor %}
                        </div>
                        {% endif%} {% endcomment %}
                    {% bootstrap_messages %}
                        {% block content %}{% endblock content %}

                        <hr/>
                        &copy: Ask Company, 제윤태
                    </div>
                </div>
            </div>

        </body>

    </html>

dev/askcompany/instagram/templates/instagram/post_archive.html
<h2>latest</h2>

{{latest}}

<h2>date_list</h2>

{% for date in date_list %}
    {{date|date:'Y'}}
    {{date.year}}<br>
{% endfor %}

dev/askcompany/instagram/templates/instagram/post_archive_year.html
<h2>year</h2>
{{year}}  <br>

<h2> previous_year</h2>
{{previous_year}}<br>

<h2> next_year</h2>
{{next_year}}<br>

<h2>date_list</h2>
{{date_list}}<br>

<h2>object_list</h2>
{{object_list}}

dev/askcompany/instagram/templates/instagram/post_confirm_delete.html
{% extends "instagram/layout.html" %}

{% block content %}
 <form action ="" method="post">
  {% csrf_token %}
   
  <div class ="alert alert-danger">
    정말 삭제하시겠습니까?
    </div>
    <a href="{{post.get_absolute_url}}" class="btn btn-secondary">
    내용 보기 
    </a>
    <input type ="submit" value="삭제하겠습니다." class="btn btn-danger"/>

    </form>
{% endblock content %}

dev/askcompany/instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}

{% block title %}
    Post Detail pk#{{post.pk}}
{% endblock %}

{% block content %}
    <h2>Author :
        {{post.author}}</h2>

    {% if post.photo%}
        <img src="{{post.photo.url}}" style="width: 100px"/>
    {% endif %}
    {{post.message|linebreaks}}
    <hr/>
    <a href="{% url 'instagram:post_list'%}" class="btn btn-primary">
        목록
    </a>
    <a href="{% url 'instagram:post_edit' post.pk %}" class="btn btn-info">
        수정
    </a>
    <a href="{% url 'instagram:post_delete' post.pk %}" class="btn btn-danger">
        삭제
    </a>
  
{% endblock content %}

dev/askcompany/instagram/templates/instagram/post_form.html
{% extends 'instagram/layout.html' %}
{% load bootstrap4 %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}  
    {% comment %} csrf_token을 호출하면 
      csrfmiddlewaretoken 으로 서버로 전달된다. POST 요청에 한해 써야한다.
      유저  Token 현재 요청이 유효한지에 대한 토큰이다
      @csrf_exmpt를 적용하면 안써도된다.
      앱 API에서는 끈다.     
      Jquery.post로 요청을 하면 django csrf jquery 를 쳐서 찾아서 적용한다
      SPA
     {% endcomment %}
     {% bootstrap_form form %}
     {% buttons %}
        <button class ="btn btn-primary">
            저장
        </button>
     {% endbuttons %}
    {% comment %} <table>
        {{form.as_table}}
        </table>
        <input type= "submit" value="저장"/>{% endcomment %}
    </form>
    <hr/> 
     {% if post %}
    <a href="{{post.get_absolute_url}}" class="btn btn-secondary">
       내용으로 
    </a>
    {% endif %} 
    <a href="{% url "instagram:post_list" %}"> 목록</a>
{% endblock %}``

dev/askcompany/instagram/templates/instagram/post_list.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}
{% block title %}
    Instagram / Post List
{% endblock title %}

{% block content %}
    {% comment %} <script>
    if (1 > 0) {
        alert("hello");
    } 
    </script> {% endcomment %}
    <form action="" method="get">
        <input type="text" name="q" value="{{q}}"/>
        <input type='submit' value="검색"/>
    </form>
    <a href="{% url 'instagram:post_new' %}" class="btn btn-primary btn-block mt-1 mb-1">새 포스팅</a>
    <table class="table table-bordered table-hover">
        <tbody>
            {% for post in post_list %}
                <tr>
                    <td>
                        {{post.pk}}
                    </td>
                    <td>

                        {{post.message}}
                    </td>
                    <td>
                        {% if post.photo%}
                            <img src="{{post.photo.url}}" style="width:100px"/>
                            {% else%}
                            No Photo
                            {% endif%}
                        </td>
                        <td>
                            <a href="{{post.get_absolute_url}}">

                                {{post.message}}
                            </td>
                        </tr>
                    {%endfor %}
                </tbody>
            </table>

            {%if is_paginated %}
                {% bootstrap_pagination page_obj size='small' justify_content='center' %}
            {% endif %}
        {% endblock content %}